### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by VivekPanyam** [Majored/rs-async-zip#111]
@Majored since it's been ~5 months since the last release, would you mind pushing a new one? Thanks!

**Comment by anatawa12** [comment]
@Majored Sorry for pinging again. 
Is there any plan to release new version of rs-async-zip? My product needs deflate64 so publishing to crates.io is prevented by this crate.

**Comment by Majored** [comment]
Apologies for the delay/lack of maintenance here - you should start to see updates start rolling out again imminently.

**Comment by Majored** [comment]
I'll go ahead and close this - I've just pushed a new version also.

https://github.com/Majored/rs-async-zip/releases/tag/v0.0.17
