### ISSUE TITLE
File permissions while writing an entry

### ISSUE THREAD

**Issue by iamd3vil** [Majored/rs-async-zip#14]
Thanks so much for creating this awesome lib.

I have been trying to archive some executables and I am able to do that but I want to preserve the executable permission. I couldn't find any obvious API to give file perms to the entries written. I am pretty new to rust so excuse me if I missed anything. If there's an API to do this please can you point me towards it?

P.S I also have no idea regarding the zip file format.

**Comment by Majored** [comment]
The main issue I see here is that the specification doesn't actually outline any support for storing permissions, so this isn't something I want to directly tackle with this crate.

It seems there's a sort of de-facto within other ZIP libraries/software that uses a field within the central directory header to store this information based upon the OS used to create the ZIP file. So exposing an API to set/read these manually is something I wouldn't mind adding.

**Comment by Majored** [comment]
I've adapted the previously-merged solution a bit further - we now have a `ZipEntryBuilder` which allows direct access to the external file attribute which I previously mentioned wanting. This type then further implements an extension trait that additional operations such as setting the UNIX permissions directly.

https://github.com/Majored/rs-async-zip/blob/8e49ab1d80158143047a217481ff4a7ac464d5be/src/entry/ext.rs#L33
