### ISSUE TITLE
Unzipping Zip64 files while streaming fails with UnexpectedHeaderError

### ISSUE THREAD

**Issue by jacklinke** [Majored/rs-async-zip#151]
This library is used in the python packing too, `uv`, for unzipping Python package Wheels (zip files) for dependencies, among other things.

I recently had an issue with one such dependency - fontawesomepro, which provides its Wheel files at a private repository based on subscribers' API key (e.g.: `https://dl.fontawesome.com/MYTOKENHERE/fontawesome-pro/python/simple/`). At first I thought the issue might be with the repo or the files themselves, but it looks like it's an issue with unzipping.

I opened up an [Issue on the `uv` repo](https://github.com/astral-sh/uv/issues/8031#issuecomment-2452626747), but it was recommended that I do the same here since you will probably be able to identify if I diagnosed this correctly, and if so, help with resolution.

I provided a lot of detail in that Issue, and will copy over portions of my comments from that Issue with the details that are probably most important:

---

It looks like `uv` first started unzipping while streaming the wheels in #1157. At that point, `uv` started using the `async_zip` (aka: rs-async-zip) in a repo owned by @charliermarsh, forked from @Majored.

The error message I'm seeing, "Encountered an unexpected header (actual: 0x6064b50, expected: 0x2014b50).", is defined in [error.rs](https://github.com/charliermarsh/rs-async-zip/blob/main/src/error.rs#L65) in that package's repository with the error `UnexpectedHeaderError`.

If I am understanding the flow of the code correctly, this is what's happening:

In `CentralDirectoryReader` ([src/base/read/cd.rs](https://github.com/charliermarsh/rs-async-zip/blob/011b24604fa7bc223daaad7712c0694bac8f0a87/src/base/read/cd.rs#L44C13-L44C35)), when unzipping a streaming file we iterate through each `CentralDirectoryEntry`. We expect to either get the `CDH_SIGNATURE` for a `CentralDirectoryEntry`, or if we get [`EOCDR_SIGNATURE`]((https://github.com/charliermarsh/rs-async-zip/blob/011b24604fa7bc223daaad7712c0694bac8f0a87/src/spec/consts.rs#L16)) we consider that `OK` and end the loop. Otherwise we return an `UnexpectedHeaderError`.

The problem is that after the last `CentralDirectoryEntry`, instead of `EOCDR_SIGNATURE`, we are seeing [`ZIP64_EOCDR_SIGNATURE`](https://github.com/charliermarsh/rs-async-zip/blob/011b24604fa7bc223daaad7712c0694bac8f0a87/src/spec/consts.rs#L29C32) - which is perfectly valid for a zip64 file - but we return an `UnexpectedHeaderError` even though a perfectly good `EOCDR_SIGNATURE` is just a few bytes further away.

From the zipfile spec:

### 4.3.6
   Overall .ZIP file format:

      [local file header 1]
      [encryption header 1]
      [file data 1]
      [data descriptor 1]
      . 
      .
      .
      [local file header n]
      [encryption header n]
      [file data n]
      [data descriptor n]
      [archive decryption header] 
      [archive extra data record] 
      [central directory header 1]
      .
      .
      .
      [central directory header n]
      [zip64 end of central directory record]  <-- What cd.rs finds after last CentralDirectoryEntry
      [zip64 end of central directory locator] 
      [end of central directory record]  <-- What cd.rs expects after last CentralDirectoryEntry

---

I can't provide the whole file due to size and because I don't own the rights, but here is the beginning and end of the wheel (aka, zip). You can clearly see the last central directory header signature, the zip64 end of central directory record signature, and the end of central directory record signature.

```
50 4B 03 04 14 00 00 00 08 00 E5 9B 7C 57 00 00 
00 00 02 00 00 00 00 00 00 00 1A 00 00 00 66 6F 
6E 74 61 77 65 73 6F 6D 65 70 72 6F 2F 5F 5F 69 
6E 69 74 5F 5F 2E 70 79 03 00 50 4B 03 04 14 00 
00 00 08 00 E5 9B 7C 57 F2 89 6B 4E 73 01 00 00 
DF 02 00 00 30 00 00 00 66 6F 6E 74 61 77 65 73 
6F 6D 65 70 72 6F 2F 73 74 61 74 69 63 2F 66 6F 
6E 74 61 77 65 73 6F 6D 65 70 72 6F 2F 4C 49 43 
45 4E 53 45 2E 74 78 74 8D 51 BD 6E DB 30 10 DE 

...

0F 66 6F 6E 74 61 77 65 73 6F 6D 65 70 72 6F 2D 
36 2E 35 2E 30 2E 64 69 73 74 2D 69 6E 66 6F 2F 
57 48 45 45 4C 50 4B 01 02 14 03 14 00 00 00 08 
00 E6 9B 7C 57 AC 1A 5F A9 11 00 00 00 0F 00 00 
00 2C 00 00 00 00 00 00 00 00 00 00 00 A4 81 97 
6E C3 0F 66 6F 6E 74 61 77 65 73 6F 6D 65 70 72 
6F 2D 36 2E 35 2E 30 2E 64 69 73 74 2D 69 6E 66 
6F 2F 74 6F 70 5F 6C 65 76 65 6C 2E 74 78 74 50 
4B 01 02 14 03 14 00 00 00 08 00 5B 9C 7C 57 AE 
75 97 40 7F 93 5A 00 5A 1F 3E 01 25 00 00 00 00 
00 00 00 00 00 00 00 B4 81 F2 6E C3 0F 66 6F 6E 
74 61 77 65 73 6F 6D 65 70 72 6F 2D 36 2E 35 2E 
30 2E 64 69 73 74 2D 69 6E 66 6F 2F 52 45 43 4F 
52 44 50 4B 06 06 2C 00 00 00 00 00 00 00 2D 00 
2D 00 00 00 00 00 00 00 00 00 CF 1B 02 00 00 00 
00 00 CF 1B 02 00 00 00 00 00 DE 76 28 01 00 00 
00 00 B4 02 1E 10 00 00 00 00 50 4B 06 07 00 00 
00 00 92 79 46 11 00 00 00 00 01 00 00 00 50 4B 
05 06 00 00 00 00 FF FF FF FF DE 76 28 01 B4 02 
1E 10 00 00
```

---

I've verified on two wheels for this package that the files are good, valid zip files.

Running `zip -T fontawesomepro-6.5.0-py3-none-any.whl`: test of fontawesomepro-6.5.0-py3-none-any.whl OK

Runnning `unzip -t fontawesomepro-6.5.0-py3-none-any.whl`: No errors detected in compressed data of fontawesomepro-6.5.0-py3-none-any.whl.

Running `file fontawesomepro-6.5.0-py3-none-any.whl`: Zip archive data, at least v2.0 to extract, compression method=deflate

Running `python -m zipfile -t fontawesomepro-6.5.0-py3-none-any.whl`: Done testing

Running `7z t fontawesomepro-6.5.0-py3-none-any.whl`:

```
7-Zip 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20
 64-bit locale=en_US.UTF-8 Threads:12 OPEN_MAX:1024

Scanning the drive for archives:
1 file, 289831412 bytes (277 MiB)

Testing archive: fontawesomepro-6.5.0-py3-none-any.whl
--            
Path = fontawesomepro-6.5.0-py3-none-any.whl
Type = zip
Physical Size = 289831412
64-bit = +
Characteristics = Zip64

Everything is Ok                                                                                                               

Files: 138191
Size:       639195676
Compressed: 289831412
```

---

If there are any other details that would be helpful in resolving this or narrowing down the problem, please let me know. Thank you.

**Comment by jacklinke** [comment]
Can anyone with more knowledge in rust take a look and confirm whether my understanding of the problem is correct?

**Comment by charliermarsh** [comment]
@jacklinke -- Are you able to check out https://github.com/astral-sh/uv/pull/9110 and try running uv from source with those changes?

**Comment by charliermarsh** [comment]
Alternatively, if you can somehow share the wheel, that would be helpful too.

**Comment by jacklinke** [comment]
> @jacklinke -- Are you able to check out [astral-sh/uv#9110](https://github.com/astral-sh/uv/pull/9110) and try running uv from source with those changes?

@charliermarsh Thank you for the quick work ❤️! Sorry it took so long to get back to you, but yes!!! It's working and I can now use this in my big project. It was the only big blocker stopping me from moving to uv.

Thank you also, @zanieb
