### ISSUE TITLE
Result unwrap in ZipEntryReader::copy_to_end_crc

### ISSUE THREAD

**Issue by fenhl** [Majored/rs-async-zip#2]
The [`ZipEntryReader::copy_to_end_crc`](https://docs.rs/async_zip/0.0.3/async_zip/read/struct.ZipEntryReader.html#method.copy_to_end_crc) method panics when working with a specific zip file. I don't know whether the file is standards-compliant. If the cause of the bug is that it isn't, it should be expressed as a returned error instead of a panic.

# Steps to reproduce

Cargo.toml:

```toml
[package]
name = "async-zip-unwrap-min"
version = "0.1.0"
edition = "2021"

[dependencies]
async_zip = "=0.0.3"

[dependencies.tokio]
version = "=1.14.0"
features = ["macros", "rt-multi-thread"]
```

main.rs:

```rust
use {
    async_zip::read::stream::ZipFileReader,
    tokio::{
        fs::File,
        io,
    },
};

#[tokio::main]
async fn main() {
    let mut zip_file = File::open("BizHawk-2.7-win-x64.zip").await.expect("panic not happening here");
    let mut zip_file = ZipFileReader::new(&mut zip_file);
    while let Some(entry) = zip_file.entry_reader().await.expect("panic not happening here") {
        entry.copy_to_end_crc(&mut io::sink(), 64 * 1024).await.expect("panic not happening here");
    }
}
```

The file `BizHawk-2.7-win-x64.zip` is taken from <https://github.com/TASEmulators/BizHawk/releases/tag/2.7>.

Output:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: DecompressError(General { msg: None }) }', C:\Users\fenhl\.cargo\registry\src\github.com-1ecc6299db9ec823\async_zip-0.0.3\src\read\mod.rs:176:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Not all bytes of this reader were consumed before being dropped.', C:\Users\fenhl\.cargo\registry\src\github.com-1ecc6299db9ec823\async_zip-0.0.3\src\read\mod.rs:208:13
stack backtrace:
```

(stack backtrace for the 2nd panic omitted since that's not the bug being discussed here)

**Comment by Majored** [comment]
Should be fixed with [this](https://github.com/Majored/rs-async-zip/commit/4f2c28561e71ee9902e3ca9694c02694bf7e03c3) commit. I had incorrectly assumed the bit ordering for the general-purpose flag.

Though, this example will now still panic on the `expect()` for the Err returned by `entry_reader()` as there's currently no support for reading files that were stream written (ie. are using a data descriptor). Still gathering my thoughts on how to approach that.
