### ISSUE TITLE
Unexpected header error

### ISSUE THREAD

**Issue by azymohliad** [Majored/rs-async-zip#29]
I'm trying to open [this](https://github.com/InfiniTimeOrg/InfiniTime/releases/download/1.10.0/pinetime-mcuboot-app-dfu-1.10.0.zip) ZIP archive, but `async_zip::read::fs::ZipFileReader::new()` returns `UnexpectedHeaderError`:

```
Error: Encountered an unexpected header (actual: 0x0, expected: 0x6054b50).
```

All other tools I tried work well with this archive. I'm using `async_zip` version 0.0.8 from crates.io, rust 1.62.

**Comment by JonathanxD** [comment]
I cannot test now (I'm on windows), but I think Majored/rs-async-io-utilities#4 should fix this, I will be testing it later.

**Comment by azymohliad** [comment]
Thanks for a quick response! Just tested git version, I can also confirm that it's fixed!
