### ISSUE TITLE
ZipEntry::dir removed

### ISSUE THREAD

**Issue by fenhl** [Majored/rs-async-zip#41]
The method `ZipEntry::dir`, which checks whether the entry represents a directory, was removed in e4a0aa586696e753bb2d0340c49841186d2b159f. It's easy enough to reimplement as `entry.filename().ends_with('/')` but I'm curious why it was removed in the first place. If the removal was an oversight, it would be nice if it could be added back since it's convenient to have.

**Comment by Majored** [comment]
Mainly just an oversight, indeed - I've been trying to experiment with the API but and that meant moving additional functionality (ie. anything other than getters/setters for the raw data) into an extension trait: https://github.com/Majored/rs-async-zip/blob/main/src/entry/ext.rs

Still not sure where I want to go with the API though at the moment. Are you depending on the main branch or did you purely notice this from commits?

**Comment by fenhl** [comment]
I upgraded from 0.0.7 to 0.0.9 and ran a bisect since I wanted to see if there was an explanation in the commit message before opening this issue.

**Comment by Majored** [comment]
Oops, yeah, that was unintended. I've added back in https://github.com/Majored/rs-async-zip/commit/ac9a038508d61d33b1624712b2f11064641b33d9, thanks. 👍
