### ISSUE TITLE
Fails to compile as a dependency

### ISSUE THREAD

**Issue by temportalflux** [Majored/rs-async-zip#42]
Looks like the dependency [async_io_utilities](https://crates.io/crates/async_io_utilities) was yanked from crates.io, resulting in this crate no longer compiling as a dependency in other crates.
```
error: no matching package named `async_io_utilities` found
location searched: registry `crates-io`
required by package `async_zip v0.0.9`
    ... which satisfies dependency `async_zip = "^0.0.9"` of package ...
```

**Comment by Majored** [comment]
Thanks for letting me know - I've restored the latest version of `async_io_utilities` so that `0.0.9` compiles at the very least. 👍

**Comment by Hocuri** [comment]
@Majored is it also possible to restore the deleted https://github.com/Majored/rs-async-zip GitHub repo, to make older versions & forks like https://github.com/dignifiedquire/rs-async-zip compile?

**Comment by JonathanxD** [comment]
> @Majored is it also possible to restore the deleted https://github.com/Majored/rs-async-io-utilities GitHub repo, to make older versions & forks like https://github.com/dignifiedquire/rs-async-zip compile?

Idk what you're trying to do, and why you would like to compile old forks of rs-async-zip, but you [can use my fork of rs-async-io-utilities](https://github.com/JonathanxD/rs-async-io-utilities) instead, I cannot guarantee I will not delete it someday, but I may achieve it at some point and delete later, it doesn't make sense to keep it, but I may do for some time. There are also other forks as well.

**Comment by Hocuri** [comment]
@JonathanxD that's very nice; [we fixed the problem in the meantime](https://github.com/deltachat/deltachat-core-rust/pull/3747), so for us, you won't need to keep it.
