### ISSUE TITLE
Some weird behaviour

### ISSUE THREAD

**Issue by BeastLe9enD** [Majored/rs-async-zip#5]
Hey,
I tried to read a simple UTF8 txt file from a zip archive.
```Rust
use async_zip::read::fs::ZipFileReader;
use tokio::io::AsyncReadExt;

#[tokio::main]
async fn main() {
    let zip = ZipFileReader::new("resources.zip".to_string()).await.unwrap();
    let (index, entry) = zip.entry("content.txt").unwrap();
    let mut entry_reader = zip.entry_reader(index).await.unwrap();

    let file_length = entry.uncompressed_size().unwrap();

    let mut buffer = String::with_capacity(file_length as usize);
    let bytes_read = entry_reader.read_to_string(&mut buffer).await.unwrap();
    println!("{}:{}", bytes_read, buffer);
}
```

I get an error that the file is not utf8-encoded:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }', src\main.rs:13:69
```

So I just did a hack to see what bytes actually are inside the file:
```Rust
use async_zip::read::fs::ZipFileReader;
use tokio::io::AsyncReadExt;

#[tokio::main]
async fn main() {
    let zip = ZipFileReader::new("resources.zip".to_string()).await.unwrap();
    let (index, entry) = zip.entry("content.txt").unwrap();
    let mut entry_reader = zip.entry_reader(index).await.unwrap();

    let file_length = entry.uncompressed_size().unwrap();

    let mut buffer = Vec::with_capacity(file_length as usize);
    let bytes_read = entry_reader.read_to_end(&mut buffer).await.unwrap();
    println!("{}:{}", bytes_read, unsafe{ std::str::from_utf8_unchecked(&buffer) });
}
```

The console output is the following:
```
30:
vETF]�:       $     
```

Is there something I'm doing wrong? It seems really weird.
In case you are interested, I can send you the zip file.

**Comment by Majored** [comment]
You aren't doing anything wrong in your example. If I take an archive written via [ZipFileWriter::write_entry_whole()](https://github.com/Majored/rs-async-zip/blob/8a71467510548eb1f5feec28378bd99018294b66/src/write/mod.rs#L111), it works perfectly fine.

If you could provide the ZIP file being used, that would be very helpful.
It could just be that it's using some feature of the specification which we don't currently support, and there's not a sanity check for it.

**Comment by BeastLe9enD** [comment]
Yes, I just tried a zip file with an uncompressed txt file to ensure that its not the compression breaking things
Here is a google drive link :)
https://drive.google.com/file/d/1XDp8qIiQn9kNKECEKeoKRHuEGnuoGcKO/view?usp=sharing

**Comment by Majored** [comment]
It seems the local file header contains differing extra field data than in the central directory. My assumption was that they'd always be in sync, but that seems to be incorrect based on this spec note:

> Extra Field records that MAY contain information about a file that SHOULD 
   not be exposed SHOULD NOT be stored in the Local Header and SHOULD only 
   be written to the Central Directory where they can be encrypted.  This 
   design currently does not support streaming.
  
We currently just seek directly to the data offset using the file name length & extra field length present within the central directory header. So when the two are out of sync, we seek to the wrong place and start reading garbled data.

There doesn't seem to be any way around this other than to always read the local file header as well, which is quite annoying given most of the data is redundant when you have the central directory header.

In the meantime, you could use the `read::stream::ZipFileReader` implementation as that uses the local file header only.

**Comment by BeastLe9enD** [comment]
okay, thank you! Just for your information, it was a simple zip file I created with 7zip
