### ISSUE TITLE
Replace small reads in central directory parsing with one large read

### ISSUE THREAD

**Issue by VivekPanyam** [Majored/rs-async-zip#51]
In some zip files with large central directories, the process of initially loading the zip file can cause lots of small reads ([relevant code](https://github.com/Majored/rs-async-zip/blob/07721c34942c129156df4e7810f4b520b719e6d9/src/read/mod.rs#L65-L71)). This can be quite slow if reads to the underlying reader are expensive.

Since we already know the size of the central directory before we start parsing it (and we know we're going to read the whole thing), we could just read it all at once.

This should be as simple as reading `eocdr.size_cent_dir` bytes into a temporary buffer and passing that to `crate::read::cd` instead of passing  `&mut reader` as below.

https://github.com/Majored/rs-async-zip/blob/07721c34942c129156df4e7810f4b520b719e6d9/src/read/mod.rs#L40-L44

An alternative is for users to wrap their reader in a BufReader before passing it to `ZipFileReader`, but this isn't ideal as `CompressedReader` in this library already uses a BufReader internally. Also, users likely don't have knowledge of the central directory sizes of their files beforehand so they can't tune buffer sizes.

I can make a pull request with the solution I described above if that sounds good to you

Thanks!

**Comment by Majored** [comment]
This sounds like a good idea. I guess this will then result in the need for a heap allocation, but it seems likely the overhead of this will be far lower than the overhead of individual read calls.

**Comment by VivekPanyam** [comment]
Great! I added a PR. It uses a slightly different strategy than the one described above.

It uses a BufReader instead of a single buffer. For most reasonable central directory sizes, the BufReader acts as a single buffer of size `eocdr.size_cent_dir`, but for larger ones it uses a capped buffer size. This helps avoid large allocations if `eocdr.size_cent_dir` is something like `u32::MAX`.

**Comment by Majored** [comment]
Handled within: https://github.com/Majored/rs-async-zip/pull/52
