### ISSUE TITLE
Incorrect assumption in StoredZipEntry::data_offset

### ISSUE THREAD

**Issue by VivekPanyam** [Majored/rs-async-zip#54]
`StoredZipEntry::data_offset` computes the position of the compressed data for a particular entry by taking the position of the local file header and adding the header length and the trailing data length:

https://github.com/Majored/rs-async-zip/blob/07721c34942c129156df4e7810f4b520b719e6d9/src/entry/mod.rs#L159-L165

Unfortunately, the calculation of the trailing data length here is incorrect. Specifically, it's using the length of `self.entry.extra_field()` which is based on the `extra_field` in the central directory record. `extra_field` can have different lengths in the local file header and in the central directory record.

This leads to `data_offset` returning the wrong position and causes errors decompressing files. As far as I know, the only correct way to find `data_offset` is by reading the local file header to find the length of the `extra_field` following it.

(And if you're doing that, you can also read the length of the filename field from the local file header as well)

**Comment by Majored** [comment]
You're right.. and I've come across this fact before (the spec even suggests to omit the extra_field data for the LFH and only place it in the CDR if it needs to be private - via CD encryption) but somehow forgot about it when doing the re-write.

I would really like to keep the ability to skip reading the LFH in cases like these where it's not really needed, but I don't think there's any way around it. I'll see if I can come up with any clever ideas.

**Comment by VivekPanyam** [comment]
I'd be curious to see if you come up with something, but it may not be worth the effort.

As far as I know, the LFH + trailing data is usually fairly small (maybe in the range of ~20 to 30 bytes). And it immediately precedes the data you're going to read anyway to decompress the file.

Reading the LFH separately before decompression will cause extra read operations, but there are ways to get rid of those.

For example, you could share a BufReader between the  LFH parsing code and the decompression code. In most cases, this should make the reads issued to the underlying reader the same as the current code.

This is because the decompression code currently uses a BufReader with the default buffer size (8kb). This isn't tuned per file and since the the LFH + trailing data is significantly smaller than this buffer size, reading the LFH immediately before decompression shouldn't generally have an impact on the number of reads.

Unfortunately, I don't think there are any clever ways of avoiding reading the LFH in general (I can elaborate more on this with examples if you'd like), but the solution I described above should basically provide equivalent performance characteristics to the current code.

**Comment by VivekPanyam** [comment]
Just checking if you're okay with something like this. Without a fix, some fairly common zip files won't be readable with this library.

I'm happy to implement the above solution if you'd like
