### ISSUE TITLE
Release timeline

### ISSUE THREAD

**Issue by VivekPanyam** [Majored/rs-async-zip#57]
Do you have a planned timeline for the next release?

Also, have you considered publishing it as 0.1.0 (instead of 0.0.10) since this is a big change from previous releases?

**Comment by Majored** [comment]
I'd say 0.0.10 within the next two weeks or so. Have a fair bit of time now so should make some good progress.

As for a 0.1, I would like to release it relatively soon but I want to make sure the APIs provided are somewhat decent before that can occur.

**Comment by VivekPanyam** [comment]
That's fair. I would recommend releasing often if you can though.

Especially since cargo doesn't consider `0.0.x` versions compatible with any other version ([source](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html)), it's okay if you make breaking changes between them.

You could also publish release candidates (e.g. `0.0.10-rc.1`) if you'd like to make it more obvious that things are in flux.

This'll let other crates depend on the new APIs so you might get feedback faster

**Comment by Majored** [comment]
Just released 0.0.10 after a few changes to get the stream reader working correctly. 👍

**Comment by NobodyXu** [comment]
@Majored Can we have a new release please?

**Comment by Majored** [comment]
Just released 0.0.12. 👍 

(@NobodyXu)

**Comment by NobodyXu** [comment]
Thank you!

**Comment by Majored** [comment]
I'll go ahead and close this given this was more of just an inquiry.

I've just pushed 0.0.15 and am trying to push versions as frequently as possible when I work on the crate until I'm happy for a 0.1.

Thanks again. 👍
