### ISSUE TITLE
Merge process

### ISSUE THREAD

**Issue by VivekPanyam** [Majored/rs-async-zip#68]
Just a suggestion - when merging a PR, the "Squash and Merge" option tends to lead to a cleaner git history - especially if the individual commits within a pull request aren't particularly descriptive. This takes all the commits in a PR, squashes them into one named after the PR title, and puts it on top of `main`. You can also configure this to include the PR description.

If you do want to keep all individual commits from a PR, the "Rebase and Merge" option will stack them all on top of `main` instead of potentially interleaving them with other commits. This isn't the case for merge commits. For example, some commits from #66 are [displayed](https://github.com/Majored/rs-async-zip/commits/main) before 28a932f7ef0c29e682419bad9ab50714150c1fee even though you merged #66 after 28a932f7ef0c29e682419bad9ab50714150c1fee. "Rebase and Merge" avoids this.

Both "Squash and Merge" and "Rebase and Merge"  make the git history more readable by avoiding having several merge commits on the main branch. I'd recommend using either of those instead of merge commits.

**Comment by Majored** [comment]
I definitely want to keep the commits intact for the moment, but that might change over time if this crate grows significantly.

Will start rebasing - thanks fo the advice. 👍
