### ISSUE TITLE
Bug in `CombinedCentralDirectoryRecord`

### ISSUE THREAD

**Issue by VivekPanyam** [Majored/rs-async-zip#69]
https://github.com/Majored/rs-async-zip/blob/7808bcde7a018099a780a0175812d2d483b54992/src/read/io/combined_record.rs#L41-L43

I believe this should be `combined.directory_size = zip64eocdr.directory_size`

cc @skairunner

**Comment by skairunner** [comment]
I think so, yes. I forgot to add the directory size attribute on the Zip64 eocdr, added it later, and didn't update the combined record.

**Comment by skairunner** [comment]
Unless you're already doing something about it I'll probably work on PRs fixing this and #70 tomorrow.

**Comment by VivekPanyam** [comment]
That sounds good to me, thanks! I haven't started on these so you can go ahead

**Comment by Majored** [comment]
Fixed in https://github.com/Majored/rs-async-zip/pull/72.
