### ISSUE TITLE
Inefficient/incorrect approach to finding the zip64 EOCD locator

### ISSUE THREAD

**Issue by VivekPanyam** [Majored/rs-async-zip#70]
The current code first searches for the `EOCDR` for the zip file and then searches for a `zip64 EOCD locator`:

https://github.com/Majored/rs-async-zip/blob/7808bcde7a018099a780a0175812d2d483b54992/src/read/mod.rs#L40-L53

As far as I can tell, this repeated search is unnecessary because the `zip64 EOCD locator` is of a fixed size and immediately precedes the `EOCDR`:

```
   4.3.6 Overall .ZIP file format:

      [local file header 1]
      [encryption header 1]
      [file data 1]
      [data descriptor 1]
      . 
      .
      .
      [local file header n]
      [encryption header n]
      [file data n]
      [data descriptor n]
      [archive decryption header] 
      [archive extra data record] 
      [central directory header 1]
      .
      .
      .
      [central directory header n]
      [zip64 end of central directory record]
      [zip64 end of central directory locator] 
      [end of central directory record]
```

I think that a better approach may be to:

1. Find the `EOCDR` as normal (using the existing search code)
2. Look at the 20 bytes immediately before the `EOCDR`. If the signature matches the `zip64 EOCD locator` signature, then that's our locator. Otherwise the zip file is not a zip64

The current implementation has a few issues:
1. If the `zip64 EOCD locator` signature is in the comment at the end of the `EOCDR`, that can cause incorrect parsing
2. If the `EOCDR` has the largest possible comment, the `zip64 EOCD locator` will not be found even if it exists (because of the way the searches are implemented)
3. Both of the searches (`EOCDR` and `zip64 EOCD locator`) are implemented on top of `locate_record_by_signature` which searches up to the last ~64kb of a zip file. This can cause a repeated unnecessary search of the last 64kb which can be a problem if reads to the underlying reader are expensive.

cc @skairunner

**Comment by skairunner** [comment]
This issue should be closed as resolved @Majored
