### ISSUE TITLE
Feature request: support reading archives with utf8-incompatible metadata

### ISSUE THREAD

**Issue by citreae535** [Majored/rs-async-zip#77]
## Motivation
Although the standard has supported `UTF8` since 2006, many legacy software still create archives with utf8-incompatible metadata. In particular, the Windows Explorer's built-in ZIP archiver encodes filenames with encodings defined by the system locale setting. (For example, `CP437` for English, `CP936/GBK` for Simplified Chinese, `CP950/Big5` for Traditional Chinese. This is still the case on Windows 11.)

A ZIP library should be expected to read and extract archives with utf8-incompatible metadata.

## Current Status
`ZipFileReader` as of version 0.0.11 returns `UpstreamReadError: stream did not contain valid UTF-8` if the archive has utf8-incompatible metadata.

https://github.com/Majored/rs-async-zip/blob/d64187baeacaf03d760ac760aead766ba8829663/src/read/mod.rs#L149-L153

## Expected behavior
1. `ZipFileReader` should be able to read archives with utf8-incompatible metadata.
2. If an entry's `UTF8` flag is set, `ZipFileReader` should try to parse its metadata as Rust string.
3. If an entry's `UTF8` flag is not set, `ZipFileReader` should either return the raw bytes or try to parse the metadata with a default encoding. In the latter case, it might be useful to also return the raw bytes allowing the caller to try a different encoding.

### `zip-rs`
`zip-rs` performs a lossy conversion if the entry has a `UTF8` flag. Else, it tries to parse the metadata with `CP437`.

https://github.com/zip-rs/zip/blob/0dcc40bee0179d9e841622f6c1a2217173b69951/src/read.rs#L683-L690

### `Python`
`zipfile` module in Python's standard library has the same behavior as `zip-rs`, but allows the caller to provide an optional encoding to replace the default `CP437`.

https://github.com/python/cpython/blob/88a1e6db0ff7856191a5d63d3d26a896f3ae5885/Lib/zipfile.py#L1401-L1406

## Test Archives
The attached archives contain an empty file with the same name. One is encoded with `GBK`, the other with `UTF8`.
[gbk.zip](https://github.com/Majored/rs-async-zip/files/10523069/gbk.zip)
[utf8.zip](https://github.com/Majored/rs-async-zip/files/10523071/utf8.zip)

**Comment by Majored** [comment]
I've just push V0.0.15 which includes [ZipString](https://docs.rs/async_zip/latest/async_zip/struct.ZipString.html), so creation of readers should no longer fail with the UpstreamReadError.

Whilst it's not a full implementation with supprt for GBK/CP437/etc, it at least allows access to the raw bytes now.

**Comment by citreae535** [comment]
Thanks a lot! Access to raw bytes is sufficient for my use case.
