### ISSUE TITLE
`ZipEntryReader` is now private

### ISSUE THREAD

**Issue by NobodyXu** [Majored/rs-async-zip#79]
`ZipEntryReader` is used in public API of [`async_zip::read::stream::ZipFileReader`](https://docs.rs/async_zip/latest/async_zip/read/stream/struct.ZipFileReader.html) and it was public, but it is now private in 0.0.12

**Comment by Majored** [comment]
Looks like it was accidentally removed in a recent PR and was missed.

I've added it back & a small comment to clarify the re-export is intended as part of the public API: https://github.com/Majored/rs-async-zip/commit/26f7a47105db4bda46ad46fee1ecc8a9921cfc64
