### ISSUE TITLE
Addition of inner type which doesn't pass through shutdown() calls

### ISSUE THREAD

**Issue by Majored** [Majored/rs-async-zip#8]
As per: https://users.rust-lang.org/t/stream-data-in-compress-and-stream-out/72521/6

At current, the stream writer implementation [calls shutdown()](https://github.com/Majored/rs-async-zip/blob/4edd2a3779f6b1ccb3f3a841da2618dff9849429/src/write/entry_stream.rs#L85) on the compression writer when attempting to close the entry.

This is done as the upstream compression crate does not implement any way to finish the encoding without [calling shutdown()](https://github.com/Nemo157/async-compression/blob/7e9ecbb336b4b274840303021261443f1667355c/src/tokio/write/generic/encoder.rs#L116).
However, their implementation of the shutdown also polls the inner writer's shutdown, thus chaining the shutdown call up to the generic writer.

I don't see any way to avoid this shutdown call, but feel free to comment below if you do.
So for the time being, an inner type wrapping the generic writer should be implemented which ignores calls to poll_shutdown().

Likely want to be implemented within: https://github.com/Majored/rs-async-zip/blob/main/src/write/compressed_writer.rs

**Comment by arifd** [comment]
Hi @Majored, that was me! :)

Only reason why I didn't file this issue myself, is because one of the people who helped me identify this bug told me he was already working on a PR.

@Nemo157 author of async_compression, mentioned he's happy to provide the relevant API to solve this properly. Pinging him, in case.

**Comment by Majored** [comment]
I've gone ahead and added this inner type and your original code (without the customised DuplexStream) is now working correctly on my end.

I'll eventually get around to making a PR for `async_compression` with the API change needed for this (if no one else has), but I want to get familiar with the codebase before doing that given its heavy use of macros for code generation/abstraction.

Let me know if you still run into any issues with this.
