### ISSUE TITLE
examples->cli_compress An unexpected HeaderError (2180153824, 33639248) was reported when the compressed file was decompressed

### ISSUE THREAD

**Issue by chenshuhao** [Majored/rs-async-zip#81]
why?

**Comment by Majored** [comment]
I'm not having any issues locally when extracting an archive generated by cli_compress - running a test via `unzip -t` also yielded no issues.

Are you able to narrow down the issue specifically? 
Maybe a certain file within the directory you're trying to compress? 
What specific extracting tool are you using?

**Comment by Majored** [comment]
I'm going to go ahead and close this for the moment - feel free to reopen this if you see it.
