### ISSUE TITLE
Is it possible to provide an AsyncSeek implementation for ZipEntryReader?

### ISSUE THREAD

**Issue by jplatte** [Majored/rs-async-zip#87]
I'm not super familiar with compression in general and zip specifically.. Would it be possible to have an `AsyncSeek` implementation through which one could skip the first N (decompressed) output bytes and start reading from that point?

**Comment by Majored** [comment]
My understanding is that you could, but it's not going to be efficient as the supported compressions (namely deflate) are block-based and a block uses data from the previous blocks for its decompression. So each time you'd seek, the upstream reader would have to seek back to its start & then decompress everything up until the new cursor.

The only situation where we could implement it is where you aren't using decompression at all (ie. the Stored method).

Though, do take this with a grain of salt as I've just handed off the decompression work for this crate to `async-compression`. You might get a more informed answer over there.
