### ISSUE TITLE
Feature: data descriptors in streaming mode timeline

### ISSUE THREAD

**Issue by NobodyXu** [Majored/rs-async-zip#94]
cargo-binstall just experienced one failure due to this not supported in streaming mode.

The error message says it will get supported soon, so I wonder if there is a timeline for this, i.e. if it's going to be supported in the next release and how long it will take.

If it will take quite some time for it to be supported, we might switch to file-based API.

This is just an issue asking for the timeline, not asking for a new feature, @Majored please don't feel pressured.

**Comment by NobodyXu** [comment]
@Majored Friendly ping since this issue has been stale for more than one month

**Comment by Majored** [comment]
Apologies for the huge delay here. This has been reintroduced in the latest version.

https://github.com/Majored/rs-async-zip/releases/tag/v0.0.17

**Comment by NobodyXu** [comment]
Thank you!
