### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by fenhl** [Majored/rs-async-zip#95]
It would be useful to have a changelog explaining the breaking changes between versions.

**Comment by Majored** [comment]
A completely reasonable request given the user base of this crate has grown a fair bit. I'm looking to get a 0.1 out soon so I'll start releasing version changelogs with that. 👍

**Comment by Majored** [comment]
I'll go ahead and close this as the latest two releases have changelogs attached.

https://github.com/Majored/rs-async-zip/releases/tag/v0.0.17
