### ISSUE TITLE
How to construct ZipDateTime without chrono dependency?

### ISSUE THREAD

**Issue by tmpfs** [Majored/rs-async-zip#96]
Hi,

Thanks for the library! I want to construct a `ZipDateTime` but do not want to use `chrono` as I already use `time` directly.

I am porting from synchronous code that uses `zip` and previously I could use [this function](https://docs.rs/zip/latest/zip/struct.DateTime.html#method.from_date_and_time) but I can't see an equivalent in `ZipDateTime`.

Am I missing something?

Thanks 🙏

**Comment by Majored** [comment]
You're correct in saying this currently isn't possible without `chrono`. Will look to get this done for the next update. 👍

**Comment by tmpfs** [comment]
Thanks @Majored, appreciate it 🙏

**Comment by Majored** [comment]
This was added in the latest release - sorry for the delay here.

https://github.com/Majored/rs-async-zip/releases/tag/v0.0.17
