### ISSUE TITLE
`tokio::io::AsyncRead`(`Ext`) doesn't seem to be implemented for `async_zip::tokio::read::ZipEntryReader`

### ISSUE THREAD

**Issue by theRookieCoder** [Majored/rs-async-zip#98]
When I use `async_zip::tokio::read::seek::ZipFileReader::reader_with_entry()` to get a reader, I don't seem to be able to use tokio's `AsyncRead` or `AsyncReadExt` on it, despite using the tokio specific module. This is fine for when I only want to read (since I could use the function aliases `read_to_<end/string>_checked()`), but when I'm using something like `copy()`, having `AsyncRead` implemented is required.

**Comment by anatawa12** [comment]
I think you can use [`.compat()`](https://docs.rs/tokio-util/0.7.8/tokio_util/compat/trait.FuturesAsyncReadCompatExt.html#method.compat).

I think rs-async-zip want not to have dependencyship to tokio in core so I'm using compat for most case.

**Comment by theRookieCoder** [comment]
Can confirm, using `.compat()` fixes this. But it requires the dependency `tokio-util` and isn't documented anywhere at the moment.
